### ISSUE TITLE
Tafels reserveren (bezoeker/gebruiker)

### ISSUE THREAD

**Issue by NiLSPACE** [ICTM1h3/KratonRosbeijer#1]
Als bezoeker wil ik tafels reserveren, zodat ik kan dineren in het restaurant.

___ 

- [x] SQL-injectie vrij.
- [x] Kan niet spammen.
- [x] Beveiligd tegen Cross-site scripting.
- [x] De bezoeker kan aangeven voor hoeveel personen de reservering is.
- [x] De bezoeker kan een tijdstip kiezen voor de reservering.
- [x] ~~De bezoeker kan zien welke tafels vrij zijn op het gekozen moment.~~
- [x] ~~De bezoeker kan kiezen uit de beschikbare tafels.~~
- [x] De bezoeker kan bijzonderheden melden. 
- [x] De bezoeker moet email, naam en telefoonnummer kunnen invoeren. 
- [x] De bezoeker kan alleen reserveren als de keuken het aankan.

**Comment by NiLSPACE** [comment]
Test

**Comment by NiLSPACE** [comment]
Test2

**Comment by NiLSPACE** [comment]
@Maartenzand

**Comment by NiLSPACE** [comment]
Bla

**Comment by NiLSPACE** [comment]
![image](https://user-images.githubusercontent.com/1160867/32827351-271ab15e-c9ec-11e7-946a-a841ae8a28c7.png)



https://wireframe.cc/tAURvl

**Comment by Iris-Christiaanse** [comment]
omschrijving toegevoegd schermontwerp
