### ISSUE TITLE
Bestellen menu's (administrator)

### ISSUE THREAD

**Issue by Maartenzand** [ICTM1h3/KratonRosbeijer#10]
Als administrator wil ik kunnen bestellen, zodat ik een bestelling kan maken voor de gast. 
- [ ] De website toont alle menu items.
- [ ] De administrator kan het aantal keer dat het gerecht besteld moet worden aangeven.
- [ ] Het tijdstip om de bestelling op te halen kan worden aangegeven.
             - [ ] Kan niet na 6 uur  s'avonds bestellen.

**Comment by NiLSPACE** [comment]
@RiseM1804 heb één criteria toegevoegd.

**Comment by NiLSPACE** [comment]
Schermontwerp lijkt mij hetzelfde als in #2
