### ISSUE TITLE
Beheren restaurant informatie (administrator)

### ISSUE THREAD

**Issue by Maartenzand** [ICTM1h3/KratonRosbeijer#13]
Als administrator wil de informatie over het restaurant aanpassen zodat de klanten up-to-date informatie krijgen over het restaurant.

___

- [ ] Foto's kunnen toegevoegd worden.
- [ ] Foto's kunnen verwijderd worden.
- [ ] Beveiligd tegen SQL injecties.
- [ ] Tekst kan worden aangepast.

**Comment by NiLSPACE** [comment]
Ziet er goed uit.

**Comment by NiLSPACE** [comment]
![image](https://user-images.githubusercontent.com/1160867/32883737-7485b3c2-cab8-11e7-9107-329832b92868.png)


https://wireframe.cc/EAyClU

**Comment by Iris-Christiaanse** [comment]
omschrijving schermontwerp toegevoegd

**Comment by Maartenzand** [comment]
Schermontwerp!!!

**Comment by NiLSPACE** [comment]
Na overweging hebben wij een plugin gebruikt voor de editor in plaats van het gemaakte schermontwerp.
