### ISSUE TITLE
Inloggen op de website (administrator)

### ISSUE THREAD

**Issue by Maartenzand** [ICTM1h3/KratonRosbeijer#15]
Als administrator wil ik kunnen inloggen, zodat mijn rechten als administrator krijg.

- [ ] De administrator kan gebruikersnaam invullen.
- [ ] De administrator kan wachtwoord invullen.
- [ ] De administrator ontvangt bij het inloggen de juiste rechten.

**Comment by NiLSPACE** [comment]
Zie #7 voor schermontwerp
