### ISSUE TITLE
Beheren menukaart (administrator)

### ISSUE THREAD

**Issue by Maartenzand** [ICTM1h3/KratonRosbeijer#17]
Als administrator wil ik de menukaart beheren, zodat ik het menu kan wijzigen.

___

- [x] Er kunnen nieuwe gerechten worden toegevoegd.
- [x] Er kunnen gerechten worden verwijderd.
- [x] Er kunnen gerechten worden aangepast.
- [x] Er kunnen categorieën worden verwijderd.
    - [x] Kan alleen als er geen gerecht aangekoppeld zit.
- [x] Er kunnen categorieën worden aangemaakt.
- [x] Een gerecht kan aan een categorie toegekend worden.
- [x] Menu items kunnen worden veranderd van positie.

**Comment by NiLSPACE** [comment]
@RiseM1804 ik heb de acceptatiecriteria aangepast. Wil jij ze nog bekijken?

**Comment by RiseM1804** [comment]
https://wireframe.cc/vHxKFW Part 1

**Comment by RiseM1804** [comment]
![beheren menukaart part 1](https://user-images.githubusercontent.com/33448680/32898416-6558d552-cae8-11e7-9245-13837c86f315.PNG)
https://wireframe.cc/vHxKFW Part 1

**Comment by RiseM1804** [comment]
![beheren menukaart part 2 gerecht toevoegen](https://user-images.githubusercontent.com/33448680/32898460-857d331e-cae8-11e7-8924-e7afea6e6044.PNG)
https://wireframe.cc/UShp2I
Part 2 Gerecht toevoegen

**Comment by RiseM1804** [comment]
![beheren menukaart part 3 gerecht wijzigen](https://user-images.githubusercontent.com/33448680/32898558-bc1a3c78-cae8-11e7-9adb-62070ca93b50.PNG)
Part 3 Gerecht wijzigen
https://wireframe.cc/T8KLed

**Comment by RiseM1804** [comment]
![beheren menukaart part 4 categorie toevoegen](https://user-images.githubusercontent.com/33448680/32898584-cf2ec694-cae8-11e7-9633-91a69fcb923d.PNG)
Part 4 Categorie toevoegen
https://wireframe.cc/GzOrsP

**Comment by Iris-Christiaanse** [comment]
omschrijving schermontwerp toegevoegd
