### ISSUE TITLE
Beheren reserveringen (administrator)

### ISSUE THREAD

**Issue by Maartenzand** [ICTM1h3/KratonRosbeijer#18]
Als administrator wil ik de reserveringen beheren, zodat ik de reserveringen kan wijzigen.

___

- [ ] Reserveringen kunnen geannuleerd worden.
- [ ] Reserveringen kunnen toegevoegd worden.
- [ ] Bij een reservering kan het aantal personen gewijzigd worden.
- [ ] Bij een reservering kan het aantal tafels gewijzigd worden.
- [ ] Aantal tafels met personen kan worden gewijzigd worden. 
- [ ] De capaciteit van de keuken moet ingevuld kunnen worden.

**Comment by NiLSPACE** [comment]
Ik ben bezig met een schermontwerp.

**Comment by RiseM1804** [comment]
![beheren reserveringen part 2 aanpassen reservering](https://user-images.githubusercontent.com/33448680/32949147-0b8e28f0-cba2-11e7-9792-0f0409b16f00.PNG)
Part 2 Aanpassen Reserveringen
https://wireframe.cc/x5nMER

**Comment by Iris-Christiaanse** [comment]
omschrijving schermontwerp toegevoegd
