### ISSUE TITLE
Beheren vacatures (administrator)

### ISSUE THREAD

**Issue by Maartenzand** [ICTM1h3/KratonRosbeijer#19]
Als administrator wil ik de vacatures kunnen beheren, zodat ik nieuw personeel kan aannemen.

___

- [x] Vacatures kunnen aangemaakt worden.
    - [ ] Vacatures kunnen alleen aangemaakt worden als alle benodigde informatie is gegeven.
- [x] Vacatures kunnen gesloten worden.
- [x] Vacatures kunnen aangepast worden.

**Comment by RiseM1804** [comment]
https://wireframe.cc/yrwIId Part 1 Beginscherm

**Comment by RiseM1804** [comment]
![beheren vacature part 1 begin scherm](https://user-images.githubusercontent.com/33448680/32940972-7e87b9c0-cb84-11e7-985c-74c741c8f181.PNG)
Part 1 Beginscherm
https://wireframe.cc/yrwIId

**Comment by RiseM1804** [comment]
![beheren vacature part 2 vacature aanmaken](https://user-images.githubusercontent.com/33448680/32940996-99fc8a5a-cb84-11e7-838b-0f8df084fa02.PNG)
Part 2 Vacature Aanmaken
https://wireframe.cc/trG9JT

**Comment by RiseM1804** [comment]
![beheren vacature part 3 vacature sluiten](https://user-images.githubusercontent.com/33448680/32941026-bacea36c-cb84-11e7-8bf5-a114b14b1243.PNG)
Part 3 Vacature Sluiten
https://wireframe.cc/CUuz7v

**Comment by RiseM1804** [comment]
![beheren vacature part 4 vacature wijzigen](https://user-images.githubusercontent.com/33448680/32941045-cace6e0a-cb84-11e7-850f-5759fb621fe0.PNG)
Part 4 Vacature Wijzigen
https://wireframe.cc/GEMuDA

**Comment by Iris-Christiaanse** [comment]
Niels ik ben hier bezig

**Comment by Iris-Christiaanse** [comment]
Alle schermontwerpen hebben een omschrijving
