### ISSUE TITLE
Menu bestellen (bezoeker)

### ISSUE THREAD

**Issue by Maartenzand** [ICTM1h3/KratonRosbeijer#2]
Als bezoeker wil ik kunnen bestellen, zodat ik eten kan afhalen bij het restaurant. 

___ 

- [ ] Kan niet spammen.
- [ ] SQL-injectie vrij.
- [ ] Beveiligd tegen Cross-site scripting.
- [ ] De website toont alle menu items.
- [ ] De gast kan het aantal keer dat het gerecht besteld moet worden aangeven.
- [ ] Het tijdstip om de bestelling op te halen kan worden aangegeven.
    - [ ] Kan niet na 6 uur 's avonds bestellen.

**Comment by NiLSPACE** [comment]
@RiseM1804 criteria lijken mij goed. Ik heb nog één extra toegevoegd over het tijdstip.

**Comment by NiLSPACE** [comment]
![image](https://user-images.githubusercontent.com/1160867/32828130-9524d254-c9ee-11e7-8aa0-fb0d5cf8478a.png)

https://wireframe.cc/OulE1e

**Comment by Maartenzand** [comment]
In het schermontwerp moet ook nog een optie komen waarbij de klant korting kan toepassen.

**Comment by Maartenzand** [comment]
Nog een schermontwerp ivp met de korting?

**Comment by Iris-Christiaanse** [comment]
omschrijving schermontwerp toegevoegd
