### ISSUE TITLE
Beheren accounts (administrator)

### ISSUE THREAD

**Issue by Maartenzand** [ICTM1h3/KratonRosbeijer#20]
Als administrator wil ik toegang hebben tot de accounts, zodat ik de accounts kan beheren.

- [x] Beveiligd tegen SQL injecties.
- [x] Beveiligd tegen Cross-site scripting.
- [x] Krijgt overzicht van alle accounts (het liefst met meerdere pagina's als er te veel accounts zijn)
- [x] Kan een VIP-status toevoegen aan een gebruiker. 
- [x] Kan bij de VIP-status de korting invoeren. 
- [x] Kan een VIP-status verwijderen bij een gebruiker. 
- [x] Kan gegevens van gebruikers aanpassen.
- [x] Kan accounts verwijderen.

**Comment by NiLSPACE** [comment]
Ben nu bezig met schermontwerp hiervoor

**Comment by Iris-Christiaanse** [comment]
Er zijn omschrijvingen toegevoegd aan de schermontwerpen.

**Comment by Iris-Christiaanse** [comment]
#8 #53
