### ISSUE TITLE
Registreren account (bezoeker)

### ISSUE THREAD

**Issue by NiLSPACE** [ICTM1h3/KratonRosbeijer#21]
Als een bezoeker wil ik een account kunnen registreren zodat ik een account heb.

___ 

- [x] Is SQL injectie vrij.
- [x] Is beveiligd tegen Cross-site scripting.
- [x] Een bezoeker kan niet meer dan `X` aantal gebruikers binnen een bepaalde tijd maken.
- [x] E-mail, voornaam en achternaam zijn verplichte velden.
- [x] De bezoeker moet de registratie verifiëren via email.

**Comment by NiLSPACE** [comment]
@RiseM1804 heb één criteria toegevoegd.

**Comment by RiseM1804** [comment]
![registreren](https://user-images.githubusercontent.com/33448680/32886828-427d5d3a-cac2-11e7-9581-5995cf80c337.PNG)
https://wireframe.cc/58CJyW

**Comment by NiLSPACE** [comment]
Dit scherm ontwerp vind ik goed.

**Comment by Iris-Christiaanse** [comment]
Er moet nog een schermontwerp komen voor de foutmelding als 1 of meerdere verplichte velden niet zijn ingevuld.

**Comment by Iris-Christiaanse** [comment]
Ik heb een omschrijving toegevoegd aan het schermontwerp

**Comment by RiseM1804** [comment]
![registreren part 2 foutmelding](https://user-images.githubusercontent.com/33448680/32948793-cac2732c-cba0-11e7-99ab-643281f22b67.PNG)
Part 2 Foutmelding
https://wireframe.cc/MUNzox

**Comment by Iris-Christiaanse** [comment]
Niels ik ben hier bezig

**Comment by Iris-Christiaanse** [comment]
Omschrijving is toegevoegd aan de schermontwerpen
