### ISSUE TITLE
Wachtwoord wijzigen (gebruiker)

### ISSUE THREAD

**Issue by RiseM1804** [ICTM1h3/KratonRosbeijer#22]
Als gebruiker wil ik mijn wachtwoord wijzigen, zodat ik mijn wachtwoord kan veranderen als ik die vergeten ben.
___

- [ ] Moet geverifieerd  worden via e-mail.
    - [ ] Link in email mag maar één keer gebruikt worden. 
- [ ] E-mail moet in het database staan.

**Comment by RiseM1804** [comment]
![wachtwoord wijzigen part 1](https://user-images.githubusercontent.com/33448680/32885159-f25baa0a-cabc-11e7-8a7e-05b0ab8111e0.PNG)
https://wireframe.cc/aU6MCr

**Comment by RiseM1804** [comment]
![wachtwoord wijzigen part 2](https://user-images.githubusercontent.com/33448680/32885172-fd440584-cabc-11e7-87af-2d982308fa43.PNG)
https://wireframe.cc/5sgSez

**Comment by NiLSPACE** [comment]
Ik vind deze schermontwerpen goed.

**Comment by Iris-Christiaanse** [comment]
Ik heb bij beide schermontwerpen een beschrijving toegevoegd
