### ISSUE TITLE
Beheren bestellingen (administrator)

### ISSUE THREAD

**Issue by Maartenzand** [ICTM1h3/KratonRosbeijer#24]
Als administrator wil ik inzicht hebben op de bestellingen, zodat ik de bestellingen kan beheren.
- [ ] De administrator heeft inzicht over de bestellingen. 
- [ ] De administrator kan de bestellingen annuleren.
- [ ] De administrator kan de bestellingen die klaar zijn afvinken.

**Comment by RiseM1804** [comment]
https://wireframe.cc/FsjJv1 Part 1

**Comment by RiseM1804** [comment]
![beheren bestelling part 1](https://user-images.githubusercontent.com/33448680/32948542-e6d5e9dc-cb9f-11e7-82b9-5e7d3c9f5544.PNG)
Part 1
https://wireframe.cc/FsjJv1

**Comment by RiseM1804** [comment]
![beheren bestelling part 2 bestelling wijzigen](https://user-images.githubusercontent.com/33448680/32948600-17940d1a-cba0-11e7-9537-9f0395de413d.PNG)
Part 2 Bestelling Wijzigen
https://wireframe.cc/rr9L9c

**Comment by Iris-Christiaanse** [comment]
omschrijving schermontwerp toegevoegd
