### ISSUE TITLE
Inzien vacatures (bezoeker)

### ISSUE THREAD

**Issue by Maartenzand** [ICTM1h3/KratonRosbeijer#34]
Als bezoeker wil ik de vacatures kunnen inzien, zodat ik kan kijken of ik kan solliciteren voor deze vacature.

- [ ] Krijgt overzicht van alle vacatures.
- [ ] Krijgt te zien hoe hij kan reageren op een vacature.

**Comment by RiseM1804** [comment]
![inzien vacatures](https://user-images.githubusercontent.com/33448680/32937693-cf399010-cb79-11e7-9fe9-3048610b1c89.PNG)
https://wireframe.cc/gfgodp

**Comment by Iris-Christiaanse** [comment]
Ik heb een omschrijving toegevoegd aan het scherm ontwerp
