### ISSUE TITLE
Inzien restaurant info (bezoeker)

### ISSUE THREAD

**Issue by Maartenzand** [ICTM1h3/KratonRosbeijer#4]
Als een bezoeker wil ik informatie over het restaurant zien zodat ik er wat meer over weet.

___

- [ ] Moet exact te zien zijn zoals #13 het invoert.

**Comment by NiLSPACE** [comment]
![image](https://user-images.githubusercontent.com/1160867/32850228-e1a3bd3c-ca31-11e7-92fd-eb2bbe40d7f2.png)

https://wireframe.cc/sV8Qof

**Comment by Iris-Christiaanse** [comment]
omschrijving toegevoegd schermontwerp
