### ISSUE TITLE
Menukaart inzien (bezoeker)

### ISSUE THREAD

**Issue by Maartenzand** [ICTM1h3/KratonRosbeijer#5]
Als bezoeker wil ik de menukaart in kunnen zien, zodat ik weet wat ik kan bestellen. 
___ 

- [x] Beveiligd tegen Cross-site scripting.
- [x] Het menukaart kan gedownload worden.
- [x] Moet te zien zijn, zoals #17 het invoert.

**Comment by NiLSPACE** [comment]
![image](https://user-images.githubusercontent.com/1160867/32850689-1f0b1de0-ca33-11e7-96ea-4ac1ad05de5b.png)

https://wireframe.cc/uu2bmb

**Comment by Iris-Christiaanse** [comment]
omschrijving schermontwerp toegevoegd

**Comment by Maartenzand** [comment]
fix pdf fout
