### ISSUE TITLE
Tafels reserveren (bezoeker)

### ISSUE THREAD

**Issue by Maartenzand** [ICTM1h3/KratonRosbeijer#55]
Als bezoeker wil ik tafels kunnen reserveren, zodat ik kan eten in het restaurant.
- [x]  E-mail aan klant na het bevestigen van de reservering met het volgende:
	- [x]  Naam van de reserveerder.
	- [x]  E-mail van de reserveerder.
	- [x]  Telefoonnummer van de reserveerder.
	- [ ]  ~Tafel met capaciteit.~
	- [x]  Datum met tijdsstip.
	- [x]  Tijdsduur van de reservering.
	- [x]  Bijzonderheden.
	- [x]  Status van de reservering is geactiveerd.
- [x]  Bij een groep (meer dan 12 personen): 
	- [x]  De eigenaar belt de klant zelf op. 
	- [x]  Anders moet er contact opgenomen worden met het restaurant.
	- [x]  De status van de reservering is geactiveerd.
- [x]  Status van de reservering:
	- [x]  Geactiveerd bij normale reservering.
	- [x]  Gedeactiveerd bij een groepsreservering (meer dan 12 personen).

**Comment by NiLSPACE** [comment]
@Maartenzand ik zie hier nu dat je ook wilt dat de tafel met capaciteit meegestuurd word, maar dat hoeft de klant helemaal niet te weten.
