### ISSUE TITLE
Cadeaukaart bestellen (bezoeker)

### ISSUE THREAD

**Issue by Maartenzand** [ICTM1h3/KratonRosbeijer#6]
Als bezoeker wil ik een cadeaukaart kunnen bestellen, zodat ik een etentje weg kan geven.
___ 

- [ ] Kan niet spammen.
- [ ] SQL-injectie vrij.
- [ ] Beveiligd tegen Cross-site scripting.
- [ ] De bezoeker kan kiezen hoeveel waarde de cadeaubon heeft.
- [ ] De bezoeker kan de cadeaubon afrekenen.
- [ ] De administrator hoeft niet te betalen voor de aangemaakte cadeaukaart.

**Comment by RiseM1804** [comment]
![cadeaukaart bestellen](https://user-images.githubusercontent.com/33448680/32946610-8252e962-cb98-11e7-806b-c1b1f39cf1f1.PNG)
https://wireframe.cc/ukO3wK

**Comment by Iris-Christiaanse** [comment]
omschrijving schermontwerp toegevoegd
