### ISSUE TITLE
Inloggen op de website (gebruiker)

### ISSUE THREAD

**Issue by Maartenzand** [ICTM1h3/KratonRosbeijer#7]
Als bezoeker wil ik kunnen inloggen, zodat ik mijn rechten als gebruiker kan gebruiken.
___ 

- [x] SQL-injectie vrij.
- [x] De bezoeker kan gebruikersnaam invullen.
- [x] De bezoeker kan wachtwoord invullen.

**Comment by NiLSPACE** [comment]
Ziet er goed uit @RiseM1804.

**Comment by Maartenzand** [comment]
Graag ook een schermontwerp van wachtwoord vergeten.

**Comment by RiseM1804** [comment]
![wachtwoord wijzigen part 1](https://user-images.githubusercontent.com/33448680/32946638-a5b32cd2-cb98-11e7-807f-9aa7897b6f1c.PNG)
![wachtwoord wijzigen part 2](https://user-images.githubusercontent.com/33448680/32946643-aa70e53e-cb98-11e7-9f47-49ed7615530d.PNG)

**Comment by NiLSPACE** [comment]
#22

**Comment by Iris-Christiaanse** [comment]
schermontwerp wachtwoord vergeten omschrijving toegevoegd
