### ISSUE TITLE
Korting krijgen (VIP-gebruiker)

### ISSUE THREAD

**Issue by Maartenzand** [ICTM1h3/KratonRosbeijer#8]
Als VIP-gebruiker wil ik korting kunnen ontvangen, zodat ik het kan toepassen bij het bestellen van eten.

___ 

- [ ] SQL-injectie vrij.
- [ ] De gast kan zien of hij/zij in aanmerking komt voor korting en/of acties, die zijn toegewezen door de administrator ( #20 ).

**Comment by NiLSPACE** [comment]
@ICTM1h3 is deze ticket wel nodig? We hebben #7 al voor inloggen. Dit gaat specifiek over korting.

**Comment by Iris-Christiaanse** [comment]
Geen schermontwerp nodig
