### ISSUE TITLE
Reserveren (administrator)

### ISSUE THREAD

**Issue by Maartenzand** [ICTM1h3/KratonRosbeijer#9]
Als administrator wil ik kunnen reserveren, zodat ik een reservering kan maken voor de gast.

___ 

- [ ] De administrator kan aangeven voor hoeveel personen de reservering is.
- [ ] De administrator kan een tijdstip kiezen voor de reservering.
- [ ] De administrator kan zien welke tafels vrij zijn op het gekozen moment.
- [ ] De administrator kan kiezen uit de beschikbare tafels.

**Comment by NiLSPACE** [comment]
Schermontwerp lijkt mij hetzelfde als in #1
